config/routes.rb
Rails.application.routes.draw do
  namespace :app do
    get 'sites/patient'
    post 'sites/search'
    get 'sites/result/:id', to: 'sites#result', as: 'sites_result'
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'app/sites#patient'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/disease.rb
class Disease < ApplicationRecord
	validates :keluhan_utama, presence: true
	validates :kode_penyakit, presence: true
	validates :nama_penyakit, presence: true
	validates :gejala_gejala, presence: true

  belongs_to :history

  accepts_nested_attributes_for :history
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :histories
	validates :nama, presence: true
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
  has_one :disease, dependent: :destroy
  has_one :medicine_recipe, dependent: :destroy

	enum poli_tujuan: { "Umum":1, "Gigi":0}

	validates :no_urut, presence: true
	validates :poli_tujuan, presence: true

  accepts_nested_attributes_for :medicine_recipe
  accepts_nested_attributes_for :disease

  after_create do
    self.no_rekam_medis = self.id
    self.save
  end
end

app/models/medicine_recipe.rb
class MedicineRecipe < ApplicationRecord
	validates :kodeobat, presence: true
	validates :namaobat, presence: true
	validates :tanggal_kadaluarsa, presence: true

  belongs_to :history
  accepts_nested_attributes_for :history
end

app/models/patient.rb
class Patient < ApplicationRecord
	enum pelayanan: { "BPJS":1, "Non BPJS":0}
	enum jenis_kelamin: { "Laki laki":1, Perempuan:0}

	validates :nama_lengkap, presence: true
	validates :no_telepon, presence: true
	validates :pelayanan, presence: true
	validates :jenis_kelamin, presence: true
	validates :tempat_lahir, presence: true
	validates :tanggal_lahir, presence: true

  has_one :patient_info, dependent: :destroy
  has_many :histories, dependent: :destroy

  accepts_nested_attributes_for :patient_info, allow_destroy: true
  accepts_nested_attributes_for :histories, allow_destroy: true

  after_create :construct_number

  private
  def construct_number
    self.no = "#{self.id}#{Time.now.to_s[0..9].remove('-')}".to_i
    self.save
  end
end

app/models/patient_info.rb
class PatientInfo < ApplicationRecord
	validates :provinsi, presence: true
	validates :kota, presence: true
	validates :kecamatan, presence: true
	validates :alamat, presence: true

  belongs_to :patient
  accepts_nested_attributes_for :patient
end

app/controllers/app/sites_controller.rb
class App::SitesController < ApplicationController
  def patient
  end

  def search
    @patient = Patient.find_by_no(params[:patient][:no])
    if @patient
      redirect_to app_sites_result_path @patient.no
    else
      flash.notice = 'Nomor Pasien tidak ditemukan'
      redirect_to app_sites_patient_path
    end
  end

  def result
    @patient = Patient.find_by_no params[:id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/app/sites_helper.rb
module App::SitesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/app/sites/_form.html.erb
<%= form_for :patient, url: app_sites_search_path do |form| %>
  <div class="form-group">
    <%= form.text_field :no, class: 'form-control', placeholder: 'Nomor Pasien' %>
  </div>

  <div class="form-group">
    <%= form.submit 'Submit', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/app/sites/patient.html.erb
<div class="jumbotron">
  <h2 class="text-primary">Selamat Datang di Klinik Medika Karawaci</h2>
  <p>Silahkan masukan Nomor Pasien Anda untuk melihat Riwayat Berobat Anda di Klinik Medika Karawaci dimanapun dan kapanpun.</p>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    <p class="lead">Masukan Nomor Pasien Anda</p>
    <small>Nomor Pasien digunakan untuk melihat Riwayat Berobat Anda pada Klikik Medika</small>

    <%= render 'form', patient: @patient %>
  </div>
</div>

app/views/app/sites/result.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title">Info Pasien</h3>
      </div>
      <div class="panel-body">
        <p><strong>Nama Lengkap</strong> : <%= @patient.nama_lengkap %></p>
        <p><strong>Nomor Pasien</strong> : <%= @patient.no %></p>
        <p><strong>Nomor Telepon</strong> : <%= @patient.no_telepon %></p>
        <p><strong>Jenis Pelayanan</strong> : <%= @patient.pelayanan %></p>
        <p><strong>Jenis Kelamin</strong> : <%= @patient.jenis_kelamin %></p>
        <p><strong>Tempat, Tanggal Lahir</strong> : <%= @patient.tempat_lahir %>, <%= @patient.tanggal_lahir.to_s[0..-14] %></p>
      </div>
    </div>

    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Riwayat Berobat Pasien</h3>
      </div>
      <div class="panel-body">
        <% @patient.histories.each do |history| %>
          <p><strong>Nomor Rekam Medis</strong> : <%= history.no_rekam_medis %></p>
          <p><strong>Nomor Urut</strong> : <%= history.no_urut %></p>
          <p><strong>Poli Tujuan</strong> : <%= history.poli_tujuan %></p>
          <p><strong>Dokter yang menangani</strong> : <%= history.doctor.nama %></p>
          <p><strong>Penyakit</strong> : <%= history.disease.nama_penyakit %></p>
          <p><strong>Keluhan</strong> : <%= history.disease.keluhan_utama %></p>
          <p><strong>Gejala</strong> : <%= history.disease.gejala_gejala %></p>
          <p><strong>Pemberian Obat</strong> : <%= history.medicine_recipe.namaobat %></p>
          <p><strong>Tanggal Kadaluarsa Obat</strong> : <%= history.medicine_recipe.tanggal_kadaluarsa %></p>
          <hr>
        <% end %>
        <% if @patient.histories.empty? %>
          <p>Info Kosong</p>
        <% end %>
      </div>
    </div>


  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Klinik Karawaci Medika</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/navbar' %>
    <%= render 'partials/notification' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Klinik Medika</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/partials/_notification.html.erb
<% if notice %>
  <div class="alert alert-dismissible alert-info col-md-3 col-md-offset-9">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <p><%= notice %></p>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <p><%= alert %></p>
  <% end %>
</div>